# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v0449gRpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fv0449gRpc.proto\x12\tv0449gRpc\"\x1b\n\x0b\x64\x61taRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1a\n\x08\x64\x61ta2Plc\x12\x0e\n\x06xmlSer\x18\x01 \x01(\t\"\x1f\n\x0cslaveReq2Plc\x12\x0f\n\x07request\x18\x01 \x01(\x05\"\x1a\n\x08\x64\x61ta2Hmi\x12\x0e\n\x06xmlSer\x18\x01 \x01(\t\"\x1b\n\ndata2PlcJs\x12\r\n\x05jsSer\x18\x01 \x01(\t\"\x1b\n\ndata2HmiJs\x12\r\n\x05jsSer\x18\x01 \x01(\t\"\x1c\n\ndata2PlcPb\x12\x0e\n\x06xmlSer\x18\x01 \x01(\t\"\x1d\n\ndataAnswer\x12\x0f\n\x07message\x18\x01 \x01(\t2\x93\x01\n\x0cv0449gRpcSvc\x12=\n\x0bxchRtDataJs\x12\x15.v0449gRpc.data2PlcJs\x1a\x15.v0449gRpc.data2HmiJs\"\x00\x12\x44\n\x10xchRtDataJsSlave\x12\x17.v0449gRpc.slaveReq2Plc\x1a\x15.v0449gRpc.data2HmiJs\"\x00\x62\x06proto3')



_DATAREQUEST = DESCRIPTOR.message_types_by_name['dataRequest']
_DATA2PLC = DESCRIPTOR.message_types_by_name['data2Plc']
_SLAVEREQ2PLC = DESCRIPTOR.message_types_by_name['slaveReq2Plc']
_DATA2HMI = DESCRIPTOR.message_types_by_name['data2Hmi']
_DATA2PLCJS = DESCRIPTOR.message_types_by_name['data2PlcJs']
_DATA2HMIJS = DESCRIPTOR.message_types_by_name['data2HmiJs']
_DATA2PLCPB = DESCRIPTOR.message_types_by_name['data2PlcPb']
_DATAANSWER = DESCRIPTOR.message_types_by_name['dataAnswer']
dataRequest = _reflection.GeneratedProtocolMessageType('dataRequest', (_message.Message,), {
  'DESCRIPTOR' : _DATAREQUEST,
  '__module__' : 'v0449gRpc_pb2'
  # @@protoc_insertion_point(class_scope:v0449gRpc.dataRequest)
  })
_sym_db.RegisterMessage(dataRequest)

data2Plc = _reflection.GeneratedProtocolMessageType('data2Plc', (_message.Message,), {
  'DESCRIPTOR' : _DATA2PLC,
  '__module__' : 'v0449gRpc_pb2'
  # @@protoc_insertion_point(class_scope:v0449gRpc.data2Plc)
  })
_sym_db.RegisterMessage(data2Plc)

slaveReq2Plc = _reflection.GeneratedProtocolMessageType('slaveReq2Plc', (_message.Message,), {
  'DESCRIPTOR' : _SLAVEREQ2PLC,
  '__module__' : 'v0449gRpc_pb2'
  # @@protoc_insertion_point(class_scope:v0449gRpc.slaveReq2Plc)
  })
_sym_db.RegisterMessage(slaveReq2Plc)

data2Hmi = _reflection.GeneratedProtocolMessageType('data2Hmi', (_message.Message,), {
  'DESCRIPTOR' : _DATA2HMI,
  '__module__' : 'v0449gRpc_pb2'
  # @@protoc_insertion_point(class_scope:v0449gRpc.data2Hmi)
  })
_sym_db.RegisterMessage(data2Hmi)

data2PlcJs = _reflection.GeneratedProtocolMessageType('data2PlcJs', (_message.Message,), {
  'DESCRIPTOR' : _DATA2PLCJS,
  '__module__' : 'v0449gRpc_pb2'
  # @@protoc_insertion_point(class_scope:v0449gRpc.data2PlcJs)
  })
_sym_db.RegisterMessage(data2PlcJs)

data2HmiJs = _reflection.GeneratedProtocolMessageType('data2HmiJs', (_message.Message,), {
  'DESCRIPTOR' : _DATA2HMIJS,
  '__module__' : 'v0449gRpc_pb2'
  # @@protoc_insertion_point(class_scope:v0449gRpc.data2HmiJs)
  })
_sym_db.RegisterMessage(data2HmiJs)

data2PlcPb = _reflection.GeneratedProtocolMessageType('data2PlcPb', (_message.Message,), {
  'DESCRIPTOR' : _DATA2PLCPB,
  '__module__' : 'v0449gRpc_pb2'
  # @@protoc_insertion_point(class_scope:v0449gRpc.data2PlcPb)
  })
_sym_db.RegisterMessage(data2PlcPb)

dataAnswer = _reflection.GeneratedProtocolMessageType('dataAnswer', (_message.Message,), {
  'DESCRIPTOR' : _DATAANSWER,
  '__module__' : 'v0449gRpc_pb2'
  # @@protoc_insertion_point(class_scope:v0449gRpc.dataAnswer)
  })
_sym_db.RegisterMessage(dataAnswer)

_V0449GRPCSVC = DESCRIPTOR.services_by_name['v0449gRpcSvc']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATAREQUEST._serialized_start=30
  _DATAREQUEST._serialized_end=57
  _DATA2PLC._serialized_start=59
  _DATA2PLC._serialized_end=85
  _SLAVEREQ2PLC._serialized_start=87
  _SLAVEREQ2PLC._serialized_end=118
  _DATA2HMI._serialized_start=120
  _DATA2HMI._serialized_end=146
  _DATA2PLCJS._serialized_start=148
  _DATA2PLCJS._serialized_end=175
  _DATA2HMIJS._serialized_start=177
  _DATA2HMIJS._serialized_end=204
  _DATA2PLCPB._serialized_start=206
  _DATA2PLCPB._serialized_end=234
  _DATAANSWER._serialized_start=236
  _DATAANSWER._serialized_end=265
  _V0449GRPCSVC._serialized_start=268
  _V0449GRPCSVC._serialized_end=415
# @@protoc_insertion_point(module_scope)
