# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pingpong.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epingpong.proto\"\x15\n\x04Ping\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\"\x15\n\x04Pong\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x32)\n\x0fPingPongService\x12\x16\n\x04ping\x12\x05.Ping\x1a\x05.Pong\"\x00\x62\x06proto3')



_PING = DESCRIPTOR.message_types_by_name['Ping']
_PONG = DESCRIPTOR.message_types_by_name['Pong']
Ping = _reflection.GeneratedProtocolMessageType('Ping', (_message.Message,), {
  'DESCRIPTOR' : _PING,
  '__module__' : 'pingpong_pb2'
  # @@protoc_insertion_point(class_scope:Ping)
  })
_sym_db.RegisterMessage(Ping)

Pong = _reflection.GeneratedProtocolMessageType('Pong', (_message.Message,), {
  'DESCRIPTOR' : _PONG,
  '__module__' : 'pingpong_pb2'
  # @@protoc_insertion_point(class_scope:Pong)
  })
_sym_db.RegisterMessage(Pong)

_PINGPONGSERVICE = DESCRIPTOR.services_by_name['PingPongService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PING._serialized_start=18
  _PING._serialized_end=39
  _PONG._serialized_start=41
  _PONG._serialized_end=62
  _PINGPONGSERVICE._serialized_start=64
  _PINGPONGSERVICE._serialized_end=105
# @@protoc_insertion_point(module_scope)
